init:
  - git config --global core.autocrlf true

environment:
  matrix:
    - node_js: Stable
    - node_js: 8

platform:
  - x86
  - x64

matrix:
  allow_failures:
    - platform: x86

install:
  - ps: Install-Product node $env:node_js $env:platform
  - npm install -g npm
  - npm install -g node-gyp
  - npm install -g mocha
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off
deploy: off
